import { PdfDoc } from './pdfKit'
import type { ManufacturingProject } from '../types'

export function generateSizeChartPdf(p: ManufacturingProject): Blob {
  const pdf = new PdfDoc('Size Chart')
  pdf.cover(p, `Graded measurement chart · ${p.sizes.join(' / ')}`)
  pdf.section('Measurement Chart (cm)')
  pdf.table(
    ['Code', 'Point of measure', ...p.sizes, 'Tolerance'],
    p.measurements.map((r) => [r.code, r.point, ...p.sizes.map((s) => r.values[s].toFixed(1)), `±${r.toleranceCm.toFixed(1)}`]),
    [0.5, 2.4, ...p.sizes.map(() => 0.6), 0.7],
  )
  pdf.section('Measurement Guide')
  pdf.bullets([
    'All measurements are half-body (HB) unless noted, taken flat with garment relaxed.',
    'Chest is measured 1cm below the armhole seam-to-seam.',
    'Body length is measured from the highest point of shoulder (HPS) to hem.',
    'Grading is consistent across the size run; confirm the sealed sample before bulk.',
    `Applied tolerance per point is listed above; out-of-tolerance measurements are rejected.`,
  ])
  return pdf.finalizeAndBlob()
}

export function generateProductionNotesPdf(p: ManufacturingProject): Blob {
  const pdf = new PdfDoc('Production Notes')
  pdf.cover(p, 'Special instructions, washing & finishing')
  pdf.section('Special Instructions')
  pdf.bullets(p.notes.special)
  pdf.section('Washing & Care')
  pdf.kv([
    ['Washing', p.notes.washing],
    ['Finishing', p.notes.finishing],
  ])
  pdf.section('Wash & Distressing')
  pdf.kv([
    ['Vintage wash', p.notes.vintageWash],
    ['Distressing', p.notes.distressing],
  ])
  pdf.section('Embroidery')
  pdf.paragraph(p.notes.embroideryNotes)
  pdf.section('Quality Checkpoints')
  pdf.bullets([
    'Inline inspection at 20% and 80% of the production run.',
    'AQL 2.5 for major, 4.0 for minor defects on final inspection.',
    'Metal detection pass required before packing.',
    'Retain 1 approved sample per size as the production standard.',
  ])
  return pdf.finalizeAndBlob()
}

export function generateColorReferencesPdf(p: ManufacturingProject): Blob {
  const pdf = new PdfDoc('Color References')
  pdf.cover(p, 'HEX · RGB · Pantone')
  pdf.section('Approved Colorway')
  // swatch grid
  const doc = pdf.doc
  let yy = 78 + 60 // after section
  // draw swatches manually via table + colored chips
  p.colors.forEach((c) => {
    const x = pdf.margin
    doc.setFillColor(c.rgb[0], c.rgb[1], c.rgb[2])
    doc.roundedRect(x, yy - 12, 34, 34, 5, 5, 'F')
    doc.setDrawColor(220, 220, 224)
    doc.roundedRect(x, yy - 12, 34, 34, 5, 5, 'S')
    doc.setTextColor(18, 18, 24)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(11)
    doc.text(c.name, x + 48, yy)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    doc.setTextColor(120, 120, 132)
    doc.text(`HEX ${c.hex}    RGB ${c.rgb.join(', ')}    ${c.pantone}`, x + 48, yy + 15)
    yy += 48
  })
  return pdf.finalizeAndBlob()
}

export function generatePackagingGuidePdf(p: ManufacturingProject): Blob {
  const pdf = new PdfDoc('Packaging Guide')
  pdf.cover(p, 'Folding, labelling & carton specification')
  pdf.section('Folding')
  pdf.bullets([
    'Fold to A4 footprint (21 × 29.7 cm), sleeves tucked, logo facing up.',
    'Insert tissue between folds for premium garments.',
  ])
  pdf.section('Labelling & Tags')
  pdf.kv([
    ['Hangtag', 'Left chest, looped with tonal cord'],
    ['Care label', 'Heat-transfer, inner side seam'],
    ['Size sticker', 'Bottom-right of polybag'],
    ['Barcode', 'EAN-13, on hangtag reverse'],
  ])
  pdf.section('Polybag')
  pdf.kv([
    ['Material', 'Recycled LDPE, min 30% PCR'],
    ['Warning', 'Suffocation warning printed, self-seal'],
  ])
  pdf.section('Carton')
  pdf.kv([
    ['Assortment', 'Solid color, ratio S1 M2 L2 XL2 XXL1'],
    ['Master carton', '5-ply, max 12 kg, 60 × 40 × 40 cm'],
    ['Marking', 'Style number, color, size ratio, PO#, carton n/N'],
  ])
  return pdf.finalizeAndBlob()
}

export function generateReadmePdf(p: ManufacturingProject): Blob {
  const pdf = new PdfDoc('README')
  pdf.cover(p, 'Manufacturing package contents')
  pdf.section('About this package')
  pdf.paragraph(
    `This manufacturing package was generated by loom studios. It contains everything required for sampling and production of "${p.meta.styleName}" (${p.meta.styleNumber}). All specifications are derived directly from the design project — no placeholder data.`,
  )
  pdf.section('Contents')
  pdf.bullets([
    'TechPack.pdf — full production specification',
    'SizeChart.pdf — graded measurement chart',
    'BOM.xlsx — bill of materials (editable)',
    'ProductionNotes.pdf — special instructions, wash & finishing',
    'ColorReferences.pdf — HEX / RGB / Pantone',
    'Packaging/PackagingGuide.pdf — folding, labelling & carton spec',
    'PrintAssets/ — Front, Back, Sleeves (300 DPI, transparent PNG)',
    'Logos/ — Brand.svg + Brand.ai',
    'Patterns/ — Pattern.dxf (CAD) + Pattern.pdf',
  ])
  pdf.section('Working with your factory')
  pdf.bullets([
    'Confirm all Pantone against physical lab dips before bulk.',
    'Approve a sealed size set before starting production.',
    'Any deviation from this spec must be approved in writing.',
  ])
  pdf.section('Contact')
  pdf.kv([
    ['Brand', p.meta.brand],
    ['Designer', p.meta.designer],
    ['Generated', p.meta.date],
  ])
  return pdf.finalizeAndBlob()
}
