import { jsPDF } from 'jspdf'
import { BRAND_LIME, INK, MUTED, type ManufacturingProject } from '../types'

/** A thin, branded builder over jsPDF so every document looks like one product. */
export class PdfDoc {
  doc: jsPDF
  private M = 48
  private y = 48
  readonly W: number
  readonly H: number
  private title: string

  constructor(title: string) {
    this.doc = new jsPDF({ unit: 'pt', format: 'a4' })
    this.W = this.doc.internal.pageSize.getWidth()
    this.H = this.doc.internal.pageSize.getHeight()
    this.title = title
  }

  get margin() {
    return this.M
  }

  private ensure(h: number) {
    if (this.y + h > this.H - 56) this.addPage()
  }

  addPage() {
    this.doc.addPage()
    this.y = this.M
    this.runningHeader()
  }

  private runningHeader() {
    this.doc.setFont('helvetica', 'bold')
    this.doc.setFontSize(8)
    this.doc.setTextColor(...MUTED)
    this.doc.text('loom studios', this.M, 30)
    this.doc.setFont('helvetica', 'normal')
    this.doc.text(this.title, this.W - this.M, 30, { align: 'right' })
    this.doc.setDrawColor(230, 230, 234)
    this.doc.line(this.M, 38, this.W - this.M, 38)
    this.y = 60
  }

  cover(p: ManufacturingProject, subtitle: string) {
    const { doc } = this
    doc.setFillColor(10, 10, 14)
    doc.rect(0, 0, this.W, this.H, 'F')
    // brand chip
    doc.setFillColor(...BRAND_LIME)
    doc.roundedRect(this.M, 70, 40, 40, 9, 9, 'F')
    doc.setTextColor(10, 10, 14)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(22)
    doc.text('T', this.M + 13, 98)

    doc.setTextColor(...BRAND_LIME)
    doc.setFontSize(10)
    doc.text(p.meta.brand.toUpperCase(), this.M, 150)
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(34)
    doc.text(this.title, this.M, 190)
    doc.setTextColor(170, 170, 180)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(13)
    doc.text(subtitle, this.M, 216)

    // meta block bottom
    const rows: [string, string][] = [
      ['Style name', p.meta.styleName],
      ['Style number', p.meta.styleNumber],
      ['Collection', p.meta.collection],
      ['Season', p.meta.season],
      ['Designer', p.meta.designer],
      ['Date', p.meta.date],
    ]
    let yy = this.H - 220
    doc.setDrawColor(40, 40, 48)
    doc.line(this.M, yy - 24, this.W - this.M, yy - 24)
    rows.forEach(([k, v]) => {
      doc.setTextColor(120, 120, 132)
      doc.setFontSize(10)
      doc.text(k.toUpperCase(), this.M, yy)
      doc.setTextColor(235, 235, 240)
      doc.setFontSize(12)
      doc.text(v, this.M + 130, yy)
      yy += 26
    })
    doc.setTextColor(90, 90, 100)
    doc.setFontSize(8)
    doc.text('Generated by loom studios — Manufacturing Export System', this.M, this.H - 40)

    this.addPage()
  }

  section(title: string) {
    this.ensure(40)
    this.doc.setFont('helvetica', 'bold')
    this.doc.setFontSize(13)
    this.doc.setTextColor(...INK)
    this.doc.text(title, this.M, this.y)
    // accent underline
    this.doc.setFillColor(...BRAND_LIME)
    this.doc.rect(this.M, this.y + 5, 26, 3, 'F')
    this.doc.setDrawColor(226, 226, 230)
    this.doc.line(this.M + 32, this.y + 6, this.W - this.M, this.y + 6)
    this.y += 26
  }

  kv(rows: [string, string][]) {
    this.doc.setFontSize(10)
    rows.forEach(([k, v]) => {
      this.ensure(18)
      this.doc.setFont('helvetica', 'normal')
      this.doc.setTextColor(...MUTED)
      this.doc.text(k, this.M, this.y)
      this.doc.setTextColor(...INK)
      const lines = this.doc.splitTextToSize(v || '—', this.W - this.M - (this.M + 160))
      this.doc.text(lines, this.M + 160, this.y)
      this.y += 16 + (lines.length - 1) * 13
    })
    this.y += 8
  }

  table(headers: string[], rows: string[][], weights?: number[]) {
    const inner = this.W - 2 * this.M
    const w = weights ?? headers.map(() => 1)
    const total = w.reduce((a, b) => a + b, 0)
    const x = (i: number) => this.M + (inner * w.slice(0, i).reduce((a, b) => a + b, 0)) / total
    // header
    this.ensure(24)
    this.doc.setFillColor(245, 245, 246)
    this.doc.rect(this.M, this.y - 12, inner, 22, 'F')
    this.doc.setFont('helvetica', 'bold')
    this.doc.setFontSize(8.5)
    this.doc.setTextColor(...MUTED)
    headers.forEach((h, i) => this.doc.text(h.toUpperCase(), x(i) + 6, this.y + 2))
    this.y += 18
    this.doc.setFont('helvetica', 'normal')
    this.doc.setFontSize(9)
    rows.forEach((r) => {
      this.ensure(18)
      r.forEach((c, i) => {
        this.doc.setTextColor(i === 0 ? INK[0] : 70, i === 0 ? INK[1] : 70, i === 0 ? INK[2] : 80)
        const cw = x(i + 1) - x(i) - 12
        const lines = this.doc.splitTextToSize(c, cw)
        this.doc.text(lines, x(i) + 6, this.y)
      })
      this.y += 17
      this.doc.setDrawColor(238, 238, 240)
      this.doc.line(this.M, this.y - 6, this.W - this.M, this.y - 6)
    })
    this.y += 10
  }

  paragraph(text: string) {
    this.ensure(20)
    this.doc.setFont('helvetica', 'normal')
    this.doc.setFontSize(9.5)
    this.doc.setTextColor(60, 60, 70)
    const lines = this.doc.splitTextToSize(text, this.W - 2 * this.M)
    this.doc.text(lines, this.M, this.y)
    this.y += lines.length * 13 + 8
  }

  bullets(items: string[]) {
    this.doc.setFontSize(9.5)
    items.forEach((it) => {
      this.ensure(16)
      this.doc.setTextColor(...BRAND_LIME)
      this.doc.text('•', this.M, this.y)
      this.doc.setTextColor(60, 60, 70)
      const lines = this.doc.splitTextToSize(it, this.W - 2 * this.M - 14)
      this.doc.text(lines, this.M + 14, this.y)
      this.y += lines.length * 13 + 3
    })
    this.y += 8
  }

  space(h: number) {
    this.y += h
  }

  /** Draw a full-width row of garment flats and advance the cursor. */
  flatsRow(kind: string, labels: string[]) {
    const gap = 14
    const w = (this.W - 2 * this.M - (labels.length - 1) * gap) / labels.length
    this.ensure(w + 26)
    labels.forEach((label, i) => this.flat(kind, label, this.M + i * (w + gap), this.y, w))
    this.y += w + 26
  }

  /** Draw a single garment flat sketch at an absolute position. */
  flat(kind: string, label: string, x: number, y: number, w: number) {
    const { doc } = this
    doc.setFillColor(248, 248, 249)
    doc.roundedRect(x, y, w, w, 6, 6, 'F')
    doc.setDrawColor(60, 60, 70)
    doc.setLineWidth(1)
    drawFlat(doc, kind, x + w / 2, y + w * 0.52, w * 0.32)
    doc.setLineWidth(0.2)
    doc.setTextColor(...MUTED)
    doc.setFontSize(8)
    doc.text(label, x + w / 2, y + w + 12, { align: 'center' })
  }

  finalizeAndBlob(): Blob {
    // page numbers
    const total = this.doc.getNumberOfPages()
    for (let i = 2; i <= total; i++) {
      this.doc.setPage(i)
      this.doc.setFont('helvetica', 'normal')
      this.doc.setFontSize(8)
      this.doc.setTextColor(...MUTED)
      this.doc.text(`${i - 1} / ${total - 1}`, this.W - this.M, this.H - 26, { align: 'right' })
    }
    return this.doc.output('blob')
  }
}

/** Minimal garment flat outline used in the PDFs. */
function drawFlat(doc: jsPDF, kind: string, cx: number, cy: number, s: number) {
  const top = cy - s * 1.4
  if (kind === 'pants') {
    doc.lines([[s, 0], [-s * 0.15, s * 2.6], [-s * 0.6, 0], [-s * 0.25, -s * 2], [-s * 0.25, s * 2], [-s * 0.6, 0], [-s * 0.15, -s * 2.6]], cx - s, top, [1, 1], 'S', true)
    return
  }
  if (kind === 'cap') {
    doc.ellipse(cx, cy, s, s * 0.7, 'S')
    doc.line(cx + s, cy, cx + s * 1.8, cy + s * 0.2)
    return
  }
  // top-style flat (tee/hoodie/jacket)
  doc.lines(
    [
      [s * 0.55, 0],
      [s * 0.5, s * 0.4],
      [-s * 0.35, s * 0.25],
      [0, s * 1.8],
      [-s * 1.4, 0],
      [0, -s * 1.8],
      [-s * 0.35, -s * 0.25],
      [s * 0.5, -s * 0.4],
    ],
    cx - s * 0.55,
    top,
    [1, 1],
    'S',
    true,
  )
  // neck
  doc.lines([[s * 0.3, s * 0.28], [s * 0.3, -s * 0.28]], cx - s * 0.3, top, [1, 1], 'S', false)
}
